// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sassy.cpp
void sass(std::string filename);
extern "C" SEXP _sassy_sass(SEXP filename) {
  BEGIN_CPP11
    sass(cpp11::as_cpp<cpp11::decay_t<std::string>>(filename));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_sassy_sass", (DL_FUNC) &_sassy_sass, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_sassy(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
